### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by tomviner**

### CODE REVIEW

**Comment by tomviner** [comment]
Thanks. Still needs some adjustments to get the various interpreters (and macos) working, then I'll let you know, and if you're happy, you can give travis-ci permission to get PR webhook pings and show test results in your PRs.

**Comment by tomviner** [comment]
But I can test on my fork, at https://travis-ci.org/tomviner/networkzero

**Comment by tjguk** [comment]
Thanks for this, Tom. Let me know when it's ready to go and what I 
should do to get it running and I'm happy to set things up.

**Comment by tomviner** [comment]
Will do.

**Pull request merged**
